exam_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('exam_project.accounts.urls')),
    path('', include('exam_project.games.urls')),
    path('dashboard/', include('exam_project.common.urls'))
]

exam_project/games/models.py
from enum import Enum

from django.contrib.auth import get_user_model
from django.core import validators
from django.db import models

UserModel = get_user_model()


class Choices(Enum):
    @classmethod
    def choices(cls):
        return [(x.name, x.value) for x in cls]

    @classmethod
    def max_len(cls):
        return max(len(name) for name, _ in cls.choices())


class Category(Choices):
    ACTION = "Action"
    ADVENTURE = "Adventure"
    PUZZLE = "Puzzle"
    STRATEGY = "Strategy"
    SPORTS = "Sports"
    BOARD = "Board/Card Game"
    OTHER = "Other"


class GameModel(models.Model):
    title = models.CharField(max_length=30, unique=True, null=False, blank=False, )
    category = models.CharField(max_length=Category.max_len(), choices=Category.choices(), )
    price = models.IntegerField(null=False, blank=False, validators=(validators.MinValueValidator(10),), )
    image_url = models.URLField(null=True, blank=True, )
    summary = models.TextField(null=True, blank=True, )
    user = models.ForeignKey(UserModel, default=None, on_delete=models.CASCADE, )

    def __str__(self):
        return f'{self.title}  --  {self.category}'

templates/bought_games.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}

{% if all_games %}
    <section id="welcome-world">
        {% for game in all_games %}

            <div class="game">
                <div class="image-wrap">
                    <img src="{{ game.game.image_url }}"
                         alt="UNO">
                </div>
                <h3>{{ game.game.title }}</h3>
                <h1>{{ game.game.category }}</h1>
            </div>

        {% endfor %}
    </section>

{% else %}
    <p class="no-articles">No games yet</p>

{% endif %}
{% endblock %}

templates/comment-game.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}

    <form id="create" method="post" action="{% url 'comment game' game_id=game.pk user_id=user.pk %}">
            <h1>Comment Game</h1>

              {{ form }}

            <input class="btn submit" type="submit" value="Post comment">
            {% csrf_token %}

    </form>

{% endblock %}

templates/home-page.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}

    {% if not games %}
        <p class="no-articles">No games yet</p>
    {% else %}
        <p class="no-articles">ALL NEW GAMES</p>
        <section id="welcome-world">
            {% for game in games %}
                <div class="game">

                    <div class="image-wrap">
                        <img src="{{ game.image_url }}"
                             alt="UNO">
                    </div>
                    <h3>{{ game.title }}</h3>
                    <h1>{{ game.category }}</h1>

                    <div class="data-buttons">
                        <a href="{% url 'game details' pk=game.pk %}" class="btn details-btn">Details</a>
                    </div>

                </div>
            {% endfor %}
        </section>
    {% endif %}

    <footer>
    </footer>

{% endblock %}

templates/my-games.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}

{% if not games %}
    <p class="no-articles">No games yet</p>
{% else %}

    <section id="welcome-world">
{#        {% for game in request.user.gamemodel_set.all %}#}
        {% for game in games %}

            <div class="game">
                <div class="image-wrap">
                    <img src="{{ game.image_url }}"
                         alt="UNO">
                </div>
                <h3>{{ game.title }}</h3>
                <h1>{{ game.category }}</h1>

                <div class="data-buttons">
                <a href="{% url 'game details' pk=game.pk %}" class="btn details-btn">Details</a>
                </div>

            </div>

        {% endfor %}
    </section>
{% endif %}

{% endblock %}